// 🗃️ DATABASE ENTITIES: Import analytics-related entity types
import { type DailyStats, type PageViewSource } from 'wasp/entities';

// 🚨 ERROR HANDLING: Import HTTP error utilities
import { HttpError } from 'wasp/server';

// 🔧 WASP OPERATIONS: Import operation type definitions
import { type GetDailyStats } from 'wasp/server/operations';

// 📊 TYPE DEFINITIONS: Extended analytics data structures
type DailyStatsWithSources = DailyStats & {
  sources: PageViewSource[]; // Include traffic source information
};

type DailyStatsValues = {
  dailyStats: DailyStatsWithSources; // Most recent day's analytics
  weeklyStats: DailyStatsWithSources[]; // Last 7 days of analytics
};

/**
 * 📊 ANALYTICS DATA RETRIEVAL: Get daily and weekly statistics for admin dashboard
 * 🔧 TEMPLATE USAGE: Core operation for analytics dashboard data
 * 
 * Key features:
 * - Admin-only access control
 * - Daily stats with traffic sources
 * - Weekly trending data (7 days)
 * - Graceful handling of missing data
 * - Comprehensive analytics overview
 * 
 * Security:
 * - Requires admin user authentication
 * - Returns HTTP 401 for unauthorized access
 * - No data exposure to non-admin users
 * 
 * Data structure:
 * - dailyStats: Latest day's complete analytics
 * - weeklyStats: Array of last 7 days for trending
 * - sources: Traffic source breakdown per day
 * 
 * Dependencies:
 * - dailyStatsJob: Background job that generates stats
 * - DailyStats entity: Database table for daily metrics
 * - PageViewSource entity: Traffic source tracking
 */
export const getDailyStats: GetDailyStats<void, DailyStatsValues | undefined> = async (_args, context) => {
  // 🔐 ADMIN AUTHORIZATION: Ensure only admin users can access analytics
  if (!context.user?.isAdmin) {
    throw new HttpError(401); // Unauthorized access
    // 🔧 CHANGE: Customize error response:
    // throw new HttpError(401, 'Analytics access requires admin privileges');
  }
  
  // 📈 LATEST DAILY STATS: Retrieve most recent day's analytics data
  const dailyStats = await context.entities.DailyStats.findFirst({
    orderBy: {
      date: 'desc', // Most recent date first
    },
    include: {
      sources: true, // Include traffic source breakdown
    },
  });
  
  // 🚫 HANDLE MISSING DATA: Check if analytics data exists
  if (!dailyStats) {
    console.log('\x1b[34mNote: No daily stats have been generated by the dailyStatsJob yet. \x1b[0m');
    // 🔧 CHANGE: Add more detailed logging or notifications:
    // console.warn('Analytics data missing. Check if dailyStatsJob is running properly.');
    // await notifyAdminOfMissingAnalytics();
    return undefined;
  }

  // 📊 WEEKLY TRENDING DATA: Get last 7 days for dashboard charts
  const weeklyStats = await context.entities.DailyStats.findMany({
    orderBy: {
      date: 'desc', // Newest to oldest
    },
    take: 7, // Last 7 days
    // 🔧 CHANGE: Customize time range:
    // take: 30, // Last 30 days for monthly view
    // take: 14, // Last 2 weeks for bi-weekly view
    include: {
      sources: true, // Include traffic sources for each day
    },
  });

  // 📤 RETURN ANALYTICS DATA: Provide structured analytics response
  return { dailyStats, weeklyStats };
  // 🔧 CHANGE: Add additional computed metrics:
  // return {
  //   dailyStats,
  //   weeklyStats,
  //   trends: calculateTrends(weeklyStats),
  //   topSources: aggregateTopSources(weeklyStats),
  //   growthRate: calculateGrowthRate(weeklyStats)
  // };
};

// 🔧 TEMPLATE ENHANCEMENT IDEAS:
//
// // Get analytics for specific date range
// export const getAnalyticsDateRange = async (args: { 
//   startDate: Date, 
//   endDate: Date 
// }, context) => {
//   if (!context.user?.isAdmin) throw new HttpError(401);
//   
//   return await context.entities.DailyStats.findMany({
//     where: {
//       date: {
//         gte: args.startDate,
//         lte: args.endDate
//       }
//     },
//     include: { sources: true },
//     orderBy: { date: 'asc' }
//   });
// };
//
// // Get real-time analytics summary
// export const getRealTimeStats = async (_args, context) => {
//   if (!context.user?.isAdmin) throw new HttpError(401);
//   
//   const today = new Date();
//   const todayStats = await context.entities.DailyStats.findFirst({
//     where: { date: { gte: startOfDay(today) } },
//     include: { sources: true }
//   });
//   
//   return {
//     todayStats,
//     liveVisitors: await getCurrentActiveUsers(),
//     recentPageViews: await getRecentPageViews(10)
//   };
// };
//
// // Export analytics data for reporting
// export const exportAnalyticsData = async (args: {
//   format: 'csv' | 'json',
//   dateRange: { start: Date, end: Date }
// }, context) => {
//   if (!context.user?.isAdmin) throw new HttpError(401);
//   
//   const data = await getAnalyticsDateRange(args.dateRange, context);
//   return args.format === 'csv' ? 
//     convertToCSV(data) : 
//     JSON.stringify(data, null, 2);
// };
